pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Jarodak47/TP331-frontend.git'
            }
        }

        stage('Build') {
            steps {
                script {
                    docker.build('react-app')
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    docker.image('react-app').inside {
                        sh 'npm install'
                        sh 'npm test'
                    }
                }
            }
        }

        stage('Deploy to Vercel') {
            steps {
                script {
                    sh 'vercel --prod'
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}