version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile

    image:  jarodak47/carshoponline-client:latest
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - backend
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image:  jarodak47/carshoponline-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    
